### ISSUE TITLE
Add more general tech podcasts

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-podcasts#32]
Right now, we have a few general tech podcasts but we could always use more. 

If you see a podcast that is missing, feel free to create a PR and add that suggestion to the list. 
If you are new to contributing to the repository, please read through the [contributing guidelines](https://github.com/thisdot/tech-podcasts/blob/main/CONTRIBUTING.md). 
If you need help with making your first contribution, please reach out on our [discord channel](https://discord.com/invite/u7gqGcpR56).

**Please note**
This issue will stay open so multiple people can contribute 👍

**Comment by ishan-siddiqui** [comment]
Hi! I would like to add a few podcasts - particularly from the cyber security domain..
