### ISSUE TITLE
Add more Other Technology-Specific Podcasts

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-podcasts#33]
Right now, we have a few other technology-specific podcasts but we could always use more. 

If you see a podcast that is missing, feel free to create a PR and add that suggestion to the list. 
If you are new to contributing to the repository, please read through the [contributing guidelines](https://github.com/thisdot/tech-podcasts/blob/main/CONTRIBUTING.md). 
If you need help with making your first contribution, please reach out on our [discord channel](https://discord.com/invite/u7gqGcpR56).

**Please note**
This issue will stay open so multiple people can contribute 👍

**Comment by semi-infiknight** [comment]
can u assign me this issue

**Comment by jdwilkin4** [comment]
HI @semi-infiknight ! 

Thank you for your interest in the tech podcasts repo!

We are not assigning these `hacktoberfest` issues to any one particular person because multiple people can work on this.
You are free to work on this and make as many contributions as you like. 
This issue will stay open so multiple people can contribute 👍
