### ISSUE TITLE
Add podcast descriptions to the existing list in the README

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-podcasts#38]
We already have quite a few podcasts on the list but none of them contain any descriptions. It would be nice if people knew what each of the podcasts was about. In the `README`, please provide a short 1-2 sentence description for each podcast in the list. 

Here is an example:

```md
### General JavaScript Podcasts

- [Codepen Radio](https://blog.codepen.io/radio/)
  This podcast, hosted by the CodePen team, provides insight into what it is like to run small web based software businesses. Previous guests have included Keven Powell, Kristopher Van Sant and Alex Trost.
  <br>
- [Front End Happy Hour](https://www.frontendhappyhour.com/)
  This podcast features a panel of Software Engineers from Netflix, Twitch, & Atlassian discussing everything from Frontend development, JavaScript, and software careers over a casual round of drinks. Previous guests have included Shaundai Person, Shirley Wu and Jesse Tomchak.
  <br>
```
**Please note: If you are interested in working on this, leave a comment on this issue and we will assign it to you.**

**Comment by paulaxisabel** [comment]
Hi, @jdwilkin4! I would like to work on this issue. Thank you so much!

**Comment by jdwilkin4** [comment]
@paulaxisabel 
The issue has been assigned to you
