### ISSUE TITLE
Alphabetize podcast lists and remove duplicates

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-podcasts#48]
Some of the lists are out of order and need to be alphabetized again. 
Please go through each of the categories, and sort them in alphabetical order.
We also a have few duplicates. Once the lists are in order it will be easier to spot those duplicates and remove them. 

If you are interested in working on this issue, please comment below and it will be assigned to you.
If you are new to this repository, please read through the [contributing docs](https://github.com/thisdot/tech-podcasts/blob/main/CONTRIBUTING.md) first. 

**Please note: issues will be assigned on a first come basis. Please do not start work on this issue until it has been assigned to you.**

**Comment by ShivamGarg2910** [comment]
Hi @jdwilkin4, please assign it to me

**Comment by jdwilkin4** [comment]
@ShivamGarg2910 

It has been assigned to you 👍
